title:              Hielke Maps
email:              hielkemaps@gmail.com
description:        Official Minecraft Partner
baseurl:            ""
url:                ""
author:             "Hielke Maps"
formspree_id:       "mnqzokvq"

# Social Profiles
twitter_username:   HielkeMaps

# Build settings
markdown:           kramdown
paginate:           9
paginate_path:      "/maps/:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
