title:              Hielke Maps
email:              support@hielkemaps.com
description:        Minecraft Maps by Hielke.
baseurl:            ""
url:                ""
author:             "Hielke Maps"
google_analytics:   "UA-163466455-1"

# Social Profiles
twitter_username:   HielkeMaps
discord: 6RzKxbH

# Build settings
markdown:           kramdown
paginate:           3
paginate_path:      "/maps/:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap

collections:
  maps:
    output: true
    permalink: /:collection/:path