title: Hielke Maps
email: contact@hielkemaps.com
description: Minecraft Maps by Hielke.
author: "Hielke Maps"
domain: "https://hielkemaps.com"

# Social Profiles
x_username: HielkeMaps
discord: 6RzKxbH

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap

collections:
  maps:
    output: true
    permalink: /:collection/:path
  posts:
    permalink: /news/:year-:month-:day
