title:              Hielke Maps
email:              hielkemaps@gmail.com
description:        Official Minecraft Partner
baseurl:            ""
url:                ""
author:             "Hielke Maps"

# Social Profiles
twitter_username:   HielkeMaps

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/maps/:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
