title:              Hielke Maps
email:              hielkemaps@gmail.com
description:        Minecraft Maps by Hielke.
baseurl:            ""
url:                ""
author:             "Hielke Maps"
google_analytics:   "UA-163466455-1"

# Social Profiles
x_username:   HielkeMaps
discord: 6RzKxbH

# Build settings
markdown:           kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap

collections:
  maps:
    output: true
    permalink: /:collection/:path